type = "webpack"
account_id = "3bfabc4463c2c3c340f7301d22ed18c0"
webpack_config = "webpack.config.js"

[env.dev]
name = "serlo-dev"
zone_id = "cedde9a4ab2980cd92bfc3765dc2e475"
route = "*serlo-development.dev/*"
kv-namespaces = [
    { binding = "MAINTENANCE_KV", id = "d5f281b897f643b8824881cfe2a24dd2" },
    { binding = "PACKAGES_KV", id = "19f90dc8e6ff49cd8bc42f51346409be" },
]

[env.staging]
name = "serlo-staging"
zone_id = "0067b08b108fbcf88ddaeaae4ac3d6ac"
route = "*serlo-staging.dev/*"
kv-namespaces = [
    { binding = "MAINTENANCE_KV", id = "3c3c25aba0b94b7e99f855f013f5b09c" },
    { binding = "PACKAGES_KV", id = "19f90dc8e6ff49cd8bc42f51346409be" },
]

[env.production]
name = "serlo-production"
zone_id = "1a4afa776acb2e40c3c8a135248328ae"
route = "*serlo.org/*"
kv-namespaces = [
    { binding = "MAINTENANCE_KV", id = "b1f17ebbe39c4fd9b49d1368ce225faa" },
    { binding = "PACKAGES_KV", id = "19f90dc8e6ff49cd8bc42f51346409be" },
]
