name: Wrangler
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn wrangler:publish
        env:
          CF_API_KEY: ${{ secrets.CF_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
